# SPDX-FileCopyrightText: 2023 Gabriele Pongelli
#
# SPDX-License-Identifier: MIT

# This is a basic workflow to help you get started with Actions

name: dev workflow

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  pre-checks:
    # pre-checks does not need complex matrix, project is not built
    name: Run some checks before build
    strategy:
      matrix:
        python-versions: [ "3.11" ]
        poetry-version: [ "1.3" ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      # https://github.com/actions/setup-python
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}

      # setup poetry environment without install not-yet-built package
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          poetry install --with devel --sync --no-root

      - name: Lint checks with tox
        run:
          poetry run tox --skip-pkg-install --direct-yolo -e lint

      - name: Build and check documentation
        run: poetry run tox --skip-pkg-install --direct-yolo -e docs


  build-test:
    needs: pre-checks

    name: Build on ${{ matrix.os }} - py${{ matrix.python-versions }} - poetry ${{ matrix.poetry-version }}
    # The type of runner that the job will run on
    strategy:
      fail-fast: false
      matrix:
        #python-versions: [3.8, 3.9, "3.10", "3.11"]
        #poetry-version: ["1.3"]
        #os: [ubuntu-20.04, macos-latest, windows-latest]

        # simple matrix to see if things work
        python-versions: [ "3.11" ]
        poetry-version: [ "1.3" ]
        os: [ windows-latest ]
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      # https://github.com/actions/setup-python
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      # configuration is inside pyproject.toml
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.0
        with:
          CIBW_TEST_COMMAND: >
            cd {project}
            poetry run tox --skip-pkg-install --direct-yolo -e py${{ matrix.python-versions }}

      - name: show temporary files
        run: |
          ls -l .
          ls -l ./wheelhouse/*

      # https://github.com/actions/upload-artifact
      # make artifacts available through jobs
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

      # https://github.com/codecov/codecov-action
      # Easily upload coverage reports to Codecov from GitHub Actions
      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          files: ./xml_coverage_py${{ matrix.python-versions }}.xml

