# SPDX-FileCopyrightText: 2023 Gabriele Pongelli
#
# SPDX-License-Identifier: MIT

# This is a basic workflow to help you get started with Actions

name: dev workflow

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    name: Build on ${{ matrix.os }} - py${{ matrix.python-versions }} - poetry ${{ matrix.poetry-version }}
    # The type of runner that the job will run on
    strategy:
      matrix:
        #python-versions: [3.8, 3.9, "3.10", "3.11"]
        #poetry-version: ["1.2", "1.3"]
        #os: [ubuntu-20.04, macos-latest, windows-latest]

        # simple matrix to see if things work
        python-versions: [ "3.11" ]
        poetry-version: [ "1.3" ]
        os: [ windows-latest ]
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      # https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages
      - name: Install Poetry
        run: pipx install poetry==${{ matrix.poetry-version }}

      # https://github.com/actions/setup-python
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-versions }}
          cache: 'poetry'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          poetry install --with devel --sync

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.0
        env:
          # configure cibuildwheel to build native archs ('auto'), and some emulated ones
          # https://cibuildwheel.readthedocs.io/en/stable/faq/#emulation
          # https://cibuildwheel.readthedocs.io/en/stable/options/#build-skip
          # https://github.com/pypa/cibuildwheel/blob/main/examples/github-with-qemu.yml
          CIBW_ARCHS_LINUX: x86_64 i686 arm64 arm/v7
          CIBW_ARCHS_MACOS: x86_64
          CIBW_ARCHS_WINDOWS: AMD64
          CIBW_BUILD_VERBOSITY: '3'
          CIBW_BUILD_FRONTEND: 'build'

      - name: show temporary files
        run: |
          ls -l .
          ls -l ./wheelhouse/*

      # https://github.com/actions/upload-artifact
      # make artifacts available through jobs
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

      - name: build documentation
        run: poetry run tox --skip-pkg-install --direct-yolo -e docs

      - name: linter checks with tox
        run:
          poetry run tox --skip-pkg-install --direct-yolo -e lint

      - name: test with tox
        run:
          poetry run tox --skip-pkg-install --direct-yolo -e py${{ matrix.python-versions }}

      # https://github.com/codecov/codecov-action
      # Easily upload coverage reports to Codecov from GitHub Actions
      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          files: ./xml_coverage_py${{ matrix.python-versions }}.xml

