# SPDX-FileCopyrightText: 2023 Gabriele Pongelli
#
# SPDX-License-Identifier: MIT

# This is a basic workflow to help you get started with Actions

name: stage & preview workflow

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish_dev_build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-versions: [3.9]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      # https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages
      - name: Install Poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-versions }}
          cache: 'poetry'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          poetry install --with devel --sync
      #    pip install poetry tox tox-gh-actions

      - name: test with tox
        run:
          poetry run tox --skip-pkg-install --direct-yolo -e py${{ matrix.python-versions }}

      - name: Build wheels and source tarball
        run: |
          poetry version $(poetry version --short)-dev.$GITHUB_RUN_NUMBER
          poetry version --short
          poetry build

      # https://github.com/pypa/gh-action-pypi-publish
      # needs separate account
      #- name: publish to Test PyPI
      #  uses: pypa/gh-action-pypi-publish@release/v1
      #  with:
      #    user: ${{ secrets.pypi_username }}
      #    password: ${{ secrets.pypi_password }}
      #    repository_url: https://test.pypi.org/legacy/
      #    skip_existing: true
